title: Chris Carlson
email: null
description: >- 
  Chris Carlson is a software architect, soapmaker, landscaper, pianist, and herder of tiny bio-terrorists.
baseurl: ""
url: https://chrispyduck.github.io 
domain: chrispyduck.github.io
github_username: chrispyduck
linkedin_username: chrispyduck
google_analytics: G-QDEXB4N5LL
theme: minima
plugins:
- jekyll-datapage-generator
exclude: 
- push.sh
- Gemfile
- Gemfile.lock
- README.md

header_pages:
- "professional-summary.html"
- "work-history.html"
- "projects.html"

page_gen:
- data: resume
  template: work-history-detail
  dir: work-history
  name_expr: record['_id']
- data: projects
  template: project-detail
  dir: projects
  name_expr: record['_id']
  title_expr: record['name']